#!/usr/bin/python

import subprocess
import os
import datetime

def write_packages(hostname, package_list):
    with open('generated/' + hostname + '-packages.ttl', 'w') as f:
        f.write("@prefix : <http://rny.cz/knowledge#> .\n")

        for package in package_list:
            package = package.strip()
            if not package:
                continue
            if '+' not in package:
                package = ':' + package
            else:
                package = '<http://rny.cz/knowledge#' + package + '>'
            f.write("%s :installed-on :%s .\n" % (package, hostname))

message = "Autocommit: " + datetime.datetime.now().strftime("%Y%m%d-%H%M")
os.chdir('/home/prvak/repos/public-notes')
hostname = subprocess.check_output("hostname").decode('utf-8').strip()

write_packages(
    hostname,
    subprocess.check_output("pacman -Qeq", shell=True).decode('utf-8').split('\n')
)

write_packages(
    "dragon",
    subprocess.check_output("ssh rny.cz pacman -Qeq", shell=True).decode('utf-8').split('\n')
)

assert subprocess.call(['git', 'add', '.']) == 0
if subprocess.call(['git', 'diff', '--quiet', '--exit-code', '--cached']) != 0:
    assert subprocess.call(['git', 'commit', '--all', '--quiet', '--no-status',
                            '-m', message]) == 0
    assert subprocess.call(['git', 'push']) == 0

os.chdir('/home/prvak/notes')
assert subprocess.call(['git', 'add', '.']) == 0
if subprocess.call(['git', 'diff', '--quiet', '--exit-code', '--cached']) != 0:
    assert subprocess.call(['git', 'commit', '--all', '--quiet', '--no-status',
                            '-m', message]) == 0
