#!/bin/bash

WALLPAPER_DIR="/home/prvak/Dropbox/wallpapers/"

if [ "$#" -eq 0 ]; then
	WALLPAPER=`ls $WALLPAPER_DIR | sort --random-sort | head -1`
else
	WALLPAPER="$1"
fi
feh --bg-fill $WALLPAPER_DIR$WALLPAPER
