#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	sudo $0;
	exit
fi

systemctl stop postfix
killall fetchmail

umount /home/prvak/crypto &&
umount /home/prvak/downloads &&
umount /home/prvak/fotky &&
umount /home/prvak/.bitcoin &&
umount /mnt/crypto &&
cryptsetup luksClose crypto
