#!/bin/bash

if [ $# -lt 1 ]; then
	echo "usage: $0 (executable) (gmon output)"
fi

EXEC="$1"
GMON_OUT="gmon.out"
if [ -n $2 ]; then
	GMON_OUT="$2"
fi

TMPF="/tmp/gmon2png.$$.tmp"
TMPDOT="/tmp/gmon2png.$$.dot"

OUTPNG="gmon.png"

gprof "$EXEC" "$GMON_OUT" > "$TMPF" &&
gprof2dot "$TMPF" | dot -o "$OUTPNG" -Tpng

rm -f "$TMPF"
rm -f "$TMPDOT"
