#!/usr/bin/ruby -w

Signal.trap 'INT' do
	exit 1
end

while true
	line = `mpc status | head -n 2 | tail -n 1`
	break unless line.index "[playing]"
	sleep 5
end

run = ARGV

if run.empty?
	run = [ "systemctl", "suspend" ]
end

system(*run)
