#!/usr/bin/ruby
# TODO: -w
require 'terminal-table'

require_relative 'lib/finance/homebank'

@accounting = Prvak::Homebank::Accounting.load

mode = :overview

until ARGV.empty?
	case ARGV.shift
	when "--overview"
		mode = :overview
	when "--raw-total", "--raw_total"
		mode = :raw_total
	else
		puts "Usage: homebank-balance [--overview] [--raw-total]"
		exit 1
	end
end

case mode
when :overview
	table = Terminal::Table.new do |t|
		@accounting.each_account do |account|
			t << [account.name, "%.2f" % account.total]
		end
		t << :separator
		t << ["Suma", "%.2f" % @accounting.total_value]
	end

	puts table
when :raw_total
	puts "%.2f" % @accounting.total_value
end
