#!/usr/bin/ruby
# TODO: -w

require 'iks_scrape'

# This script calculates the CZK value and current ROI of an IKS portfolio.
# Store your initial CZK investment and a list of your owned assets in
# ~/.iks-portfolio.yml like this:
#
#		$ cat ~/.iks-portfolio.yml
#		---
#		invested: 1000005
#		assets:
#			IKS Dluhopisový PLUS: 19094
#			KB Peněžní trh: 3005
#			KB Vyvážený profil: 123

require 'date'
require 'pathname'

raw = false
until ARGV.empty?
	case ARGV.shift
	when "--raw"
		raw = true
	else
		puts "Usage: iks-portfolio [--raw]"
		exit 1
	end
end

data = YAML.load_file((Pathname.new('~') + '.iks-portfolio.yml').expand_path)
assets = data["assets"] or raise "No assets owned."
invested = data["invested"] or raise "No initial investment specified"

data = IksScrape::Scraper.new.scrape

if (assets.keys - data.keys).any?
	puts "ERROR: the following assets weren't found: #{assets.keys - data.keys}"
	puts "Known assets:"
	pp data
	exit 1
end

value =
	assets.map do |name, count|
		if data.key?(name)
			data[name][:price] * count
		else
			raise "Unknown asset #{name}"
		end
	end.select { |x| x }.inject(&:+)

date = assets.map { |name, _count| data[name][:date] }.compact.max

if raw
	puts "%.2f" % value
else
	puts "%.2f Kč (%+.2f Kč / %+.2f%%%s)" % [value, value - invested, (value - invested) / invested * 100.0, date ? " @ #{date}" : ""]
end
