#!/usr/bin/ruby
# TODO: -w

require_relative 'lib/finance/iks_portfolio'

# This script calculates the CZK value and current ROI of an IKS portfolio.
# Store your initial CZK investment and a list of your owned assets in
# ~/.iks-portfolio.yml like this:
#
#		$ cat ~/.iks-portfolio.yml
#		---
#		invested: 1000005
#		assets:
#			IKS Dluhopisový PLUS: 19094
#			KB Peněžní trh: 3005
#			KB Vyvážený profil: 123

require 'date'
require 'pathname'

raw = false
until ARGV.empty?
	case ARGV.shift
	when "--raw"
		raw = true
	else
		puts "Usage: iks-portfolio [--raw]"
		exit 1
	end
end

portfolio = Prvak::Finance::IKSPortfolio.load

if raw
	puts "%.2f" % portfolio.value
else
	puts "%.2f Kč (%+.2f Kč / %+.2f%%%s)" % [
		portfolio.value,
		portfolio.gain,
		portfolio.gain_percentage,
		portfolio.date ? " @ #{portfolio.date}" : ""
	]
end
