#!/usr/bin/ruby

require 'mail'
require 'active_support/core_ext' # String#truncate

mail = Mail.read_from_string STDIN.lines.to_a.join("")
string = "#{mail.from.join ','}: #{mail.subject.truncate(20, omission: "\u2026")}"

system "xosdutilctl", "echo", string
