#!/usr/bin/ruby

require 'mail'
require 'active_support/core_ext' # String#truncate

mail = Mail.read_from_string STDIN.each_line.to_a.join("")
string = "#{mail.from.join ','}: #{mail.subject.truncate(25, omission: "...", separator: " ")}"

system "xosdutilctl", "echo", string
