#!/bin/bash

LEFT=DP2
RIGHT=VGA1

xrandr --output LVDS1 --off
xrandr --output $LEFT --auto
xrandr --output $RIGHT --auto
xrandr --output $RIGHT --right-of $LEFT
change-wallpaper &
killall xosdutil
sudo -u prvak xosdutil &

# Keyboard stuff
setxkbmap -option grp:switch,grp:alt_shift_toggle,compose:caps us,cz -variant ,qwerty
xmodmap ~/.Xmodmap

kolejnet
