#!/bin/bash

LEFT=DP2
RIGHT=HDMI3

output_connected() {
	xrandr | grep "$1 connected" > /dev/null
}

setup_displays() {
	if output_connected $LEFT && output_connected $RIGHT; then
		xrandr --output LVDS1 --off
		xrandr --output $LEFT --auto
		xrandr --output $RIGHT --auto
		xrandr --output $LEFT --rotate right
		xrandr --output $RIGHT --rotate right
		xrandr --output $RIGHT --right-of $LEFT
		change-wallpaper &
		killall xosdutil
		sudo -u prvak xosdutil &
	else
		logger "Nejsou pripojene vystupy $LEFT i $RIGHT, kaslu na to..."
		echo "Nejsou pripojene vystupy $LEFT i $RIGHT, kaslu na to..." >&2
	fi
}

setup_displays
keyboard-setup
