#!/usr/bin/ruby -w

# This watches against silent misconfigurations.

output = `postqueue -p 2>&1`.strip
exit if output =~ /Mail queue is empty/

if output =~ /mail system is down/
	# Hack: mail-queue-check should be run every 5 minutes. Mail system down
	# should be displayed maybe like once every half-hour.
	system "xosdutilctl", "echo", "Warning: mail system down" if rand(30 / 5) == 0
	exit
end

mail_lines = output.lines.select { |line|
	line =~ /^[A-Z0-9]{10} /
}

def plural(word, n)
	word + if n == 1
		""
	else
		"s"
	end
end

unsent = mail_lines.size
system "xosdutilctl", "echo", "Warning: #{unsent} unsent #{plural('mail', unsent)}"
