#!/usr/bin/ruby
# TODO: -w

# TODO: plotting

def die(*args)
	STDERR.puts(*args) unless args.empty?
	exit 1
end

require 'onlinestatus'
die unless OnlineStatus.online?

require_relative 'lib/finance/net_worth'
require 'terminal-table'
require 'pathname'
require 'csv'

LOG_PATH = "~/Dropbox/finance/net-worth.csv"

display_mode = :report
do_log = false

until ARGV.empty?
	case ARGV.shift
	when '--log'
		do_log = true
	when '--report'
		display_mode = :report
	when '--raw_total'
		display_mode = :raw_total
	when '--quiet'
		display_mode = :quiet
	else
		die "Usage: net-worth-keeper [--log] [--report / --raw_total]"
	end
end

if do_log
	CSV.open(Pathname.new(LOG_PATH).expand_path, "a") do |log|
		log << [
			Time.now.strftime("%Y-%m-%d %H:%M:%S"), Time.now.to_i,
			Prvak::Finance::NetWorth.net_worth
		] + Prvak::Finance::NetWorth.load_assets_lazy.values
	end
end

case display_mode
when :report
	table = Terminal::Table.new do |t|
		Prvak::Finance::NetWorth.load_assets_lazy.each do |asset_name, value|
			t << [asset_name, "%.2f" % value]
		end
		t << :separator
		t << ["Suma", "%.2f" % Prvak::Finance::NetWorth.net_worth]
	end
	puts table
when :raw_total
	puts "%.2f" % Prvak::Finance::NetWorth.net_worth
when :quiet
	# nothing
else
	raise
end
