#!/usr/bin/ruby
#
require 'yaml'
require 'pathname'

CONFIG=YAML.load_file(Pathname.new("~/Dropbox/finance/financial_independence.yml").expand_path)
#
# How much do I want? (monthly) (input parameter)
MONTHLY_SPENDING = CONFIG['monthly_spending']

# Monthly income
MONTHLY_INCOME = CONFIG['monthly_income']

# How much do I have?
OWNED = `net-worth-keeper --raw_total`.to_f
raise unless $?.exitstatus == 0

YEARLY_SPENDING = MONTHLY_SPENDING * 12

#########################################

YEARS_SAVED_UP = OWNED / YEARLY_SPENDING

# Compound interest rate: I = 0.04
INTEREST_RATE = 0.04

puts "Assumed compound interest rate: %.2f%%" % (INTEREST_RATE * 100)

TOTAL_YEARS = 60

puts "Total assumed years: #{TOTAL_YEARS}"

SAVINGS_RATE = 1.0 - (MONTHLY_SPENDING.to_f / MONTHLY_INCOME)
puts "Savings rate: %.2f%%" % (SAVINGS_RATE * 100)

require_relative 'lib/finance/independence'
YEARS_TO_WORK = Prvak::Finance::Independence.years_to_work(
	interest_rate: INTEREST_RATE,
	savings_rate: SAVINGS_RATE,
	total_years: TOTAL_YEARS
)

puts "Years to work: %.2f" % YEARS_TO_WORK
puts "Years saved up: %.2f" % YEARS_SAVED_UP
puts "----------------------------------------"
puts "You are %.2f%% financially independent." % ((YEARS_SAVED_UP / YEARS_TO_WORK) * 100.0)
