---
# TODO: telegram

# laptop:
#  - blueman
#  - tuxguitar
#  - dropbox
#  - qshutdown
#  - gimp
#  - krita
#  - perl
#  - slic3r
#  - steam
#  - transmission-gtk
#  - virtualbox
#  - virtualbox-dkms
#  - wireshark
#  - wine-stable
#  - acpi
#  - alarm-clock-applet
#  - android-tools-adb
#  - blender
#  - vinagre --- remote desktop
#  - zoom    --- for meetings
#  - xournal
#  - xserver-xorg-video-intel
#  - openjdk-8-jdk
#  - playonlinux
#  - rescuetime
#  - bolt   (for multiple graphic cards)
#  - ifupdown
#  - pencil2d
#  - gnupg
#  - gpgv
#  - gnupg-agent
#  - gnupg-l10n
#  - gnome-shell
#  - gnome-tweaks
#  - google-cloud-sdk
#  - google-musicmanager-beta
#  - ubuntu-desktop
#  - ubuntu-gnome-desktop
#  - ubuntu-restricted-extras
#  - chrome-gnome-shell
#  - vagrant
#  - bsdutils

- hosts: cloudragon
  vars:
    my_user: agentydragon_gmail_com
  remote_user: "{{ my_user }}"
  tasks:
  - name: add Bazel repo
    become: yes
    shell: |
      # TODO: integrity check
      curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
      echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  # TODO: update when Docker works on Eoan
  #  - name: add Docker PPA
  #    become: yes
  #    shell: |
  #      # TODO: integrity check
  #      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #      echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  #  - apt:
  #    pkg:
  #    - docker-ce
  - name: update everything
    become: yes
    apt:
      update_cache: yes
      upgrade: dist
  - name: install packages
    become: yes
    apt:
      pkg:
      - cinnamon-desktop-environment
      - curl
      - diffutils
      - fonts-powerline
      - geeqie
      - git
      - htop
      - iotop
      - iputils-ping
      - libreoffice
      - mc
      - mmv
      - mplayer
      - mpv
      - netcat-openbsd
      - nethogs
      - pkg-config
      - pv
      - pwgen
      - rcm
      - screen
      - sed
      - tree
      - vim-gtk
      - wget
      - xclip
      - zsh
  - name: install Anki
    become: yes
    apt:
      pkg:
      - anki
      - dvipng        # for Anki cards
      - fonts-roboto  # for Anki cards
      - texlive-full  # for Anki cards
      - youtube-dl    # for Anki cards
  - name: install dev env
    become: yes
    apt:
      pkg:
      - ansible
      - asciidoc
      - bazel
      - cabal-install
      - clang
      - clang-format
      - cloc
      - gcc
      - ghc
      - gitk
      - gnuplot
      - golang
      - gradle
      - jshon
      - jupyter-nbconvert
      - make
      - markdown
      - maven
      - npm
      - protobuf-compiler
      - pyqt5-dev-tools
      - python3
      - python3-pip
      - ruby
      - silversearcher-ag
      - sloccount
      - tidy  # HTML tidy
  - name: install chrome
    become: yes
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  # Installation steps for Chrome Remote Desktop.
  # https://cloud.google.com/solutions/chrome-desktop-remote-on-compute-engine
  - name: remote desktop
    block:
    - name: install chrome remote desktop, chrome
      become: yes
      apt:
        deb: https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
    - name: set 2d cinnamon
      become: yes
      copy:
        content: "exec /etc/X11/Xsession /usr/bin/cinnamon-session-cinnamon2d"
        dest: /etc/chrome-remote-desktop-session
    - name: disable screensaver to not get locked out of VM (with no password)
      block:
        - dconf:
            key: /org/cinnamon/desktop/screensaver/lock-enabled
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop/screensaver/session/idle-delay
            value: "uint32 0"
        - dconf:
            key: /org/cinnamon/settings-daemon/plugins/power/lock-on-suspend
            value: "false"
    - name: disable desktop effects (for faster remote desktop)
      block:
        - dconf:
            key: /org/cinnamon/desktop-effects
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop-effects-close-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-map-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-maximize-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-minimize-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-tile-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-unmaximize-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-on-dialogs
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop-effects-on-menus
            value: "false"
        - dconf:
            key: /org/cinnamon/enable-vfade
            value: "false"
        - dconf:
            key: /org/cinnamon/startup-animation
            value: "false"
    # fails with "no such service"
    #- name: disable display manager
    #  systemd:
    #    name: lightdm.service
    #    enabled: no

  - name: Set up dotfiles
    block:
    - name: Check to See if Git Repo Exists
      stat:
        path: "/home/{{ my_user }}/.dotfiles"
      register: stat_repo
    - name: clone dotfiles
      git:
        repo: https://github.com/agentydragon/dotfiles
        dest: "/home/{{ my_user }}/.dotfiles"
      when: stat_repo.stat.exists is not defined or stat_repo.stat.exists == false
    # TODO: maybe pull dotfiles to latest version?
    # TODO: problem: this is interactive if the files already exist.
    #  - set_fact:
    #      # Running without -f, so existing dotfiles won't be overwritten.
    #      rcup_args: "-x README.md -x LICENSE -d /home/{{ my_user }}/.dotfiles -B cloudragon"
    #  - name: Run rcup to Deploy Dotfiles
    #    command: "rcup {{ rcup_args }}"
  - name: Set up custom scripts
    block:
    - name: Check to See if Git Repo Exists
      stat:
        path: "/home/{{ my_user }}/scripts"
      register: stat_scripts
    - name: Clone scripts
      git:
        repo: https://github.com/agentydragon/scripts
        dest: "/home/{{ my_user }}/bin"
      when: stat_scripts.stat.exists is not defined or stat_scripts.stat.exists == false

  - name: Vim setup
    block:
    - name: Check Vundle
      stat:
        path: "/home/{{ my_user }}/.vim/bundle/Vundle.vim"
      register: stat_vundle
    - name: Clone Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "/home/{{ my_user }}/.vim/bundle/Vundle.vim"
      when: stat_vundle.stat.exists is not defined or stat_vundle.stat.exists == false
    - name: install vim plugins
      # https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
      shell: vim -E -c "source ~/.vimrc" -c PluginInstall -c qa
    # TODO: update Vundle

# TODO: maybe create a password for the user to avoid lock screen?
# TODO: configure anki with a password

  - name: set applets and favorite apps
    block:
    - dconf:
        key: /org/cinnamon/enabled-applets
        value: "['panel1:right:0:systray@cinnamon.org:0', 'panel1:left:0:menu@cinnamon.org:1', 'panel1:left:1:show-desktop@cinnamon.org:2', 'panel1:left:2:grouped-window-list@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:notifications@cinnamon.org:5', 'panel1:right:3:removable-drives@cinnamon.org:6', 'panel1:right:5:bluetooth@cinnamon.org:7', 'panel1:right:6:network@cinnamon.org:8', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:power@cinnamon.org:10', 'panel1:right:9:calendar@cinnamon.org:11']"
    - dconf:
        key: /org/cinnamon/favorite-apps
        value: "['cinnamon-settings.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop', 'google-chrome.desktop']"

  # TODO: might not be needed anymore
  - name: add github's key to known hosts
    blockinfile:
      path: "/home/{{ my_user }}/.ssh/known_hosts"
      create: true
      # The following key comes from the github.com pubkey as of 2020-01-24.
      # Retrieved with:
      #   ssh-keyscan -t rsa github.com
      block: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
  - name: gnome-terminal
    tags:
      - gnome-terminal
    block:
    - name: Set gnome-terminal to Solarized Light
      tags:
        - solarized
      block:
        - tempfile:
            state: directory
            suffix: gnome-terminal-solarized
          register: temp_dir
        # TODO: would be nice to check integrity, with a particular commit
        - git:
            repo: https://github.com/aruhier/gnome-terminal-colors-solarized
            dest: "{{ temp_dir.path }}"
            depth: 1
        - name: Get gnome-terminal profile UUID
          shell: >
            gsettings get org.gnome.Terminal.ProfilesList list | tr -d "[]\',"
          register: profile_uuid
        - name: Set up gnome-terminal-colors-solarized
          # dircolors are already in dotfiles.
          command: |
            dbus-launch {{ temp_dir.path }}/install.sh
              -s light
              -p {{ profile_uuid.stdout }}
              --skip-dircolors
    - name: hide gnome-terminal menu
      command: |
        gsettings set
          org.gnome.Terminal.Legacy.Settings default-show-menubar false
    # TODO: set a scrollbar policy?
    # TODO: scrollback limit - not 10k?
    # TODO: use ubuntu mono font in terminal
    # gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 150
    # TODO: set font size
  - name: Set custom datetime indicator
    block:
    - dconf:
        key: /com/canonical/indicator/datetime/time-format
        value: "'custom'"
    - dconf:
        key: /com/canonical/indicator/datetime/custom-time-format
        value: "'%Y-%m-%d %H:%M:%S'"
    - dconf:
        key: /com/canonical/indicator/datetime/show-week-numbers
        value: "true"
  - become: true
    snap:
      name:
      - telegram-desktop
  - become: true
    snap:
      classic: true
      name:
      - slack
  - name: Download Java formatter
    get_url:
      url: https://github.com/google/google-java-format/releases/download/google-java-format-1.7/google-java-format-1.7-all-deps.jar
      dest: "/home/{{ my_user }}/bin/google-java-format.jar"
  # TODO: worthy
