---
- hosts: cloudragon
  vars:
    my_user: agentydragon_gmail_com
    home_path: "/home/{{ my_user }}"
    scripts_path: "{{ home_path }}/bin"
    local_scripts_path: "{{ home_path }}/.local/bin"
    dotfiles_path: "{{ home_path }}/.dotfiles"
  remote_user: "{{ my_user }}"
  tasks:
  - file:
      path: "{{ local_scripts_path }}"
      state: directory
  # TODO: update when Docker works on Eoan
  #  - name: add Docker PPA
  #    become: yes
  #    shell: |
  #      # TODO: integrity check
  #      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #      echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  #  - apt:
  #    pkg:
  #    - docker-ce
  - include_tasks: google-repos.yaml
  - name: update everything
    become: yes
    apt:
      update_cache: yes
      upgrade: dist
  - name: install packages
    become: yes
    apt:
      pkg:
      - cinnamon-desktop-environment
      - curl
      - diffutils
      - fonts-powerline
      - geeqie
      - gimp
      - git
      - google-chrome-stable
      - htop
      - iotop
      - iputils-ping
      - libreoffice
      - mc
      - mmv
      - mplayer
      - mpv
      - netcat-openbsd
      - nethogs
      - pkg-config
      - pv
      - pwgen
      - rcm
      - screen
      - sed
      - tree
      - vim-gtk
      - vinagre
      - wget
      - xclip
      - zsh
  - include_tasks: anki.yaml
  - include_tasks: dev-env.yaml

  - include_tasks: chrome-remote-desktop.yaml

  - name: Set up dotfiles
    block:
    - name: clone dotfiles
      git:
        repo: https://github.com/agentydragon/dotfiles
        dest: "{{ dotfiles_path }}"
    # TODO: maybe pull dotfiles to latest version?
    # TODO: problem: this is interactive if the files already exist.
    #  - set_fact:
    #      # Running without -f, so existing dotfiles won't be overwritten.
    #      rcup_args: "-x README.md -x LICENSE -d {{ dotfiles_path }} -B cloudragon"
    #  - name: Run rcup to Deploy Dotfiles
    #    command: "rcup {{ rcup_args }}"
  - name: Set up custom scripts
    git:
      repo: https://github.com/agentydragon/scripts
      dest: "{{ scripts_path }}"

  - include_tasks: vim.yaml

  # TODO: configure anki with a password

  - name: set applets and favorite apps
    block:
    - dconf:
        key: /org/cinnamon/enabled-applets
        value: "['panel1:right:0:systray@cinnamon.org:0', 'panel1:left:0:menu@cinnamon.org:1', 'panel1:left:1:show-desktop@cinnamon.org:2', 'panel1:left:2:grouped-window-list@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:notifications@cinnamon.org:5', 'panel1:right:3:removable-drives@cinnamon.org:6', 'panel1:right:5:bluetooth@cinnamon.org:7', 'panel1:right:6:network@cinnamon.org:8', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:power@cinnamon.org:10', 'panel1:right:9:calendar@cinnamon.org:11']"
    - dconf:
        key: /org/cinnamon/favorite-apps
        value: "['cinnamon-settings.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop', 'google-chrome.desktop', 'telegram-desktop_telegramdesktop.desktop']"

  - name: gnome-terminal
    tags:
      - gnome-terminal
    block:
    - include_tasks: gnome-terminal-solarized.yaml
    - name: hide gnome-terminal menu
      command: |
        gsettings set
          org.gnome.Terminal.Legacy.Settings default-show-menubar false
    - name: do not use system font
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:{{ profile_uuid.stdout }}/use-system-font"
        value: "false"
    - name: set terminal font
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:{{ profile_uuid.stdout }}/font"
        value: "'Ubuntu Mono 14'"

    # TODO: set a scrollbar policy?
    # TODO: scrollback limit - not 10k?
  - include_tasks: datetime-format.yaml
  - become: true
    snap:
      name:
      - telegram-desktop
  - become: true
    snap:
      classic: true
      name:
      - slack
  - include_tasks: dev-env.yaml
  - name: Remove Blueman for server
    apt:
      name: blueman
      state: absent
  # TODO: worthy
