---
- hosts: cloudragon
  remote_user: agentydragon_gmail_com
  tasks:
  - name: update everything
    become: yes
    apt:
      update_cache: yes
      upgrade: dist
  - name: install packages
    become: yes
    apt:
      pkg:
      - anki
      - vim
      - rcm
      - cinnamon-desktop-environment
  - name: install chrome
    become: yes
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  # Installation steps for Chrome Remote Desktop.
  # https://cloud.google.com/solutions/chrome-desktop-remote-on-compute-engine
  - name: remote desktop
    block:
    - name: install chrome remote desktop, chrome
      become: yes
      apt:
        deb: https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
    - name: set 2d cinnamon
      become: yes
      copy:
        content: "exec /etc/X11/Xsession /usr/bin/cinnamon-session-cinnamon2d"
        dest: /etc/chrome-remote-desktop-session
    - name: disable screensaver to not get locked out of VM (with no password)
      block:
        - dconf:
            key: /org/cinnamon/desktop/screensaver/lock-enabled
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop/screensaver/session/idle-delay
            value: "uint32 0"
        - dconf:
            key: /org/cinnamon/settings-daemon/plugins/power/lock-on-suspend
            value: "false"
    - name: disable desktop effects (for faster remote desktop)
      block:
        - dconf:
            key: /org/cinnamon/desktop-effects
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop-effects-close-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-map-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-maximize-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-minimize-effect
            value: "'traditional'"
        - dconf:
            key: /org/cinnamon/desktop-effects-tile-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-unmaximize-effect
            value: "'none'"
        - dconf:
            key: /org/cinnamon/desktop-effects-on-dialogs
            value: "false"
        - dconf:
            key: /org/cinnamon/desktop-effects-on-menus
            value: "false"
        - dconf:
            key: /org/cinnamon/enable-vfade
            value: "false"
        - dconf:
            key: /org/cinnamon/startup-animation
            value: "false"
    # fails with "no such service"
    #- name: disable display manager
    #  systemd:
    #    name: lightdm.service
    #    enabled: no

  - name: Set up dotfiles
    block:
    - name: Check to See if Git Repo Exists
      stat:
        path: /home/agentydragon_gmail_com/.dotfiles
      register: stat_repo
    - name: clone dotfiles
      git:
        repo: https://github.com/agentydragon/dotfiles
        dest: /home/agentydragon_gmail_com/.dotfiles
      when: stat_repo.stat.exists is not defined or stat_repo.stat.exists == false
    # TODO: maybe pull dotfiles to latest version?
    # TODO: problem: this is interactive if the files already exist.
    #  - set_fact:
    #      # Running without -f, so existing dotfiles won't be overwritten.
    #      rcup_args: "-x README.md -x LICENSE -d /home/agentydragon_gmail_com/.dotfiles -B cloudragon"
    #  - name: Run rcup to Deploy Dotfiles
    #    command: "rcup {{ rcup_args }}"
  - name: Set up custom scripts
    block:
    - name: Check to See if Git Repo Exists
      stat:
        path: /home/agentydragon_gmail_com/scripts
      register: stat_scripts
    - name: Clone scripts
      git:
        repo: https://github.com/agentydragon/scripts
        dest: /home/agentydragon_gmail_com/bin
      when: stat_scripts.stat.exists is not defined or stat_scripts.stat.exists == false

  - name: Vim setup
    block:
    - name: Check Vundle
      stat:
        path: /home/agentydragon_gmail_com/.vim/bundle/Vundle.vim
      register: stat_vundle
    - name: Clone Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: /home/agentydragon_gmail_com/.vim/bundle/Vundle.vim
      when: stat_vundle.stat.exists is not defined or stat_vundle.stat.exists == false
    - name: install vim plugins
      # https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
      shell: vim -E -c "source ~/.vimrc" -c PluginInstall -c qa
    # TODO: update Vundle

# TODO: create a password for the user to avoid lock screen
# TODO: configure anki with a password

  - name: set applets and favorite apps
    block:
    - dconf:
        key: /org/cinnamon/enabled-applets
        value: "['panel1:right:0:systray@cinnamon.org:0', 'panel1:left:0:menu@cinnamon.org:1', 'panel1:left:1:show-desktop@cinnamon.org:2', 'panel1:left:2:grouped-window-list@cinnamon.org:3', 'panel1:right:1:keyboard@cinnamon.org:4', 'panel1:right:2:notifications@cinnamon.org:5', 'panel1:right:3:removable-drives@cinnamon.org:6', 'panel1:right:5:bluetooth@cinnamon.org:7', 'panel1:right:6:network@cinnamon.org:8', 'panel1:right:7:sound@cinnamon.org:9', 'panel1:right:8:power@cinnamon.org:10', 'panel1:right:9:calendar@cinnamon.org:11']"
    - dconf:
        key: /org/cinnamon/favorite-apps
        value: "['cinnamon-settings.desktop', 'org.gnome.Terminal.desktop', 'nemo.desktop', 'google-chrome.desktop']"

  # TODO: might not be needed anymore
  - name: add github's key to known hosts
    blockinfile:
      path: /home/agentydragon_gmail_com/.ssh/known_hosts
      create: true
      # The following key comes from the github.com pubkey as of 2020-01-24.
      # Retrieved with:
      #   ssh-keyscan -t rsa github.com
      block: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

  - name: set solarized light terminal colors
    block:
      - command: dconf reset -f /org/gnome/terminal/legacy
      - dconf:
          key: /org/gnome/terminal/legacy/default-show-menubar
          value: "false"
      - dconf:
          key: /org/gnome/terminal/legacy/schema-version
          value: "uint32 3"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color
          value: "'#fdfdf6f6e3e3'"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/bold-color
          value: "'#58586e6e7575'"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/bold-color-same-as-fg
          value: "false"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font
          value: "'Ubuntu Mono 9'"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color
          value: "'#65657b7b8383'"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette
          value: "['#070736364242', '#DCDC32322F2F', '#858599990000', '#B5B589890000', '#26268B8BD2D2', '#D3D336368282', '#2A2AA1A19898', '#EEEEE8E8D5D5', '#00002B2B3636', '#CBCB4B4B1616', '#58586E6E7575', '#65657B7B8383', '#838394949696', '#6C6C7171C4C4', '#9393A1A1A1A1', '#FDFDF6F6E3E3']"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font
          value: "false"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors
          value: "false"
      - dconf:
          key: /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency
          value: "false"
