#!/usr/bin/ruby

require 'pathname'
require_relative 'lib/xosdutil'

lines = IO.readlines(Pathname.new("~/zim/Blocked_Tasks.txt").expand_path)
lines.shift until lines.first.include? "Blocked Tasks"
lines.shift

5.times do
	Prvak.xosdutil_say(lines.shift)
	break if lines.empty?
end
