#!/bin/bash
#ffmpeg -f x11grab -s 1366x768 -r 30 -i :0.0 -f alsa -ac 2 -r 30 -i hw:0 video.avi
#ffmpeg -f x11grab -s 1366x768 -i :0.0 -f alsa -ac 2 -i hw:0 -sameq video.avi

# with audio
#ffmpeg -f x11grab -s 1366x768 -i :0.0 -f alsa -ac 2 -i hw:0 -vf scale=iw/1.5:-1 -qscale 0 video.avi

# no audio
ffmpeg -f x11grab -s 1366x768 -i :0.0 -an -vf scale=iw/1.5:-1 -qscale 0 video.avi
