#!/usr/bin/ruby -w

RANGE = (1..37)
computer = 1

if ARGV.size > 0
	arg = ARGV.shift
	if arg =~ /\d+/
		computer = ARGV[1]
	elsif arg == '-r'
		computer = RANGE.to_a.shuffle[0]
	end
end

exec "ssh", "pokormi2@u-pl#{computer}.ms.mff.cuni.cz", *ARGV
