#!/usr/bin/ruby -w

RANGE = (1..37)
computer = 1

if ARGV.size > 0
	case ARGV[0]
	when /\d+/
		computer = arg
	when '-r'
		computer = RANGE.to_a.shuffle[0]
	end
end

exec 'ssh', "pokormi2@u-pl#{computer}.ms.mff.cuni.cz", '-XC', *ARGV
