#!/usr/bin/ruby

# TODO: tfuj
require_relative 'btckit/bank.rb'
require_relative 'btckit/config.rb'

require_relative 'lib/finance/stocks'

class Main
	def initialize
		btckit_config = BtcKit::Config.new
		@bank = BtcKit::Bank.new(btckit_config.bank_filename)

		@raw_mode = false
		@verbose_table_mode = false
	end

	def parse_argv(argv)
		until argv.empty?
			flag = argv.shift

			case flag
			when '--raw'
				@raw_mode = true
			when '--verbose_table'
				@verbose_table_mode = true
			else
				raise "Unknown flag: #{flag}"
			end
		end
	end

	def main(argv)
		parse_argv(argv)
		@report = Prvak::Finance::Stocks::StatusReport.build(usd_to_czk: method(:usd_to_czk))

		if @verbose_table_mode
			puts @report.terminal_table
		end

		if @raw_mode
			puts @report.total_value_czk
		else
			puts '$%.2f + %d Kč (%d Kč)' % [
				@report.cash_usd + @report.stock_value_usd,
				@report.cash_czk,
				@report.total_value_czk
			]
		end
	end

	private

	def usd_to_czk(amount_in_usd)
		@bank.exchange(amount_in_usd, 'USD', 'CZK').cents
	end
end

Main.new.main(ARGV)
