#!/bin/bash

# Tries to tether my Galaxy Mini over USB.

ADB=/opt/android-sdk/platform-tools/adb
DEVICE=S55703fa20218

if $ADB devices | grep $DEVICE ; then
	$ADB shell su -c service call connectivity 15 s16 usb0
	echo "Tethering."
else
	echo "Found no device to tether."
fi

