#!/bin/bash
TODOS_FILE="todos"

# Or possibly ack
SEARCH=ag

if [ -d app ]; then
	cd app
	source $0
	cd ..
else
	$SEARCH todo -i .
fi

if [ -f "$TODOS_FILE" ]; then
	echo
	$SEARCH -i todo "$TODOS_FILE"
fi
