#!/usr/bin/ruby
require 'fileutils'
require 'pathname'

go = false
path = "~/downloads"

case ARGV[0]
when "--go"
	go = true
when String
	path = ARGV[0]
end

ARGV.shift

pattern = Pathname.new(path).expand_path.to_s + "/*"
drop = Dir[pattern].map do |f|
	if f =~ /^(.*)\((\d+)\)\.([^.]*)$/
		alt = "#$1.#$3"
		f if File.exist?(alt) && File::Stat.new(f).size == File::Stat.new(alt).size
	end
end.compact

exit if drop.empty?

drop.each do |file|
	puts file
end
puts

require 'highline'
if HighLine.new.agree("Delete the files? [y/n] ") || go
	drop.map { |p| FileUtils.rm(p) }
	puts "OK, deleted #{drop.size} files."
else
	puts "Doing nothing."
end
