#!/usr/bin/ruby
require 'fileutils'

drop = Dir["*"].map do |f|
	if f =~ /^(.*)\((\d+)\)\.([^.]*)$/
		alt = "#$1.#$3"
		f if File.exist?(alt) && File::Stat.new(f).size == File::Stat.new(alt).size
	end
end.compact

exit if drop.empty?

drop.each do |file|
	puts file
end
puts

require 'highline'
if HighLine.new.agree("Delete the files? [y/n] ") || ARGV[0] == "--go"
	drop.map { |p| FileUtils.rm(p) }
	puts "OK, deleted #{drop.size} files."
else
	puts "Doing nothing."
end
