#!/bin/sh
set -e

DIR=tmp
if [ "$1" = "--priv" ] ; then
	DIR=priv
	shift
fi
if [ -z "$1" ] ; then
	echo >&2 "Usage: $0 [--priv] <files>"
	exit 1
fi
rsync -rvzP --chmod=Du=rwx,go=rx,Fu=rw,go=r "$@" rny.cz:/srv/http/rny.cz/$DIR/
for a in "$@" ; do
	echo "http://$DIR.rny.cz/`basename "$a"`"
done
