#!/bin/bash
DIR=tmp
if [ "$1" = "--priv" ] ; then
	DIR=priv
	shift
fi
if [ -z "$1" ] ; then
	echo >&2 "Usage: $0 [--priv] <files>"
	exit 1
fi

for a in "$@"; do
	BASENAME="`basename \"$a\"`"
	ssh root@rny.cz "rm -iv /srv/http/rny.cz/$DIR/$BASENAME";
done
